version: "3.8"
services:
  db:
    container_name: db-moro-studio
    image: postgres:14.2-alpine3.15
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: moro
    ports:
      - "5439:5432"

volumes:
  db-data:
    driver: local
