import { type NextPage } from "next";
import Head from "next/head";
import { useAuth } from "~/utils/session";
import { api } from "~/utils/api";
import Image from "next/image";
import { BsInstagram } from "react-icons/bs";

const Home: NextPage = () => {
  const homepage = api.homepage.getHomepage.useQuery();
  const { session } = useAuth();
  const bg =
    "homepage.jpg";

  function rightArrow() {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth={1.5}
        stroke="currentColor"
        className="h-6 w-6"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
        />
      </svg>
    );
  }

  return (
    <>
      <Head>
        <title>Moro Studio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/Logo Morostudio Bulat Hitam.png" />
      </Head>
      <main>
        <div
          className="hero h-[calc(100vh-64px)]"
          style={{
            backgroundImage: `url(${homepage.data?.image || bg})`,
          }}
        >
          <div className="hero-overlay bg-opacity-60 object-fill"></div>
          <div className="bg-white-grey hero-content w-5/6 flex-col gap-12 rounded-lg bg-opacity-70 p-8 sm:w-3/4 sm:p-16">
            <h1 className="text-5xl font-bold">Moro Studio</h1>

            {(!session || session?.role === "user") && (
              <>
                <p>
                Raih momen tak terlupakan dengan Moro Studio, self photo studio terbaik di Jogja dan Solo. Dengan fasilitas lengkap dan tim profesional, kami menghadirkan pengalaman foto yang kreatif dan berkualitas tinggi untuk mengabadikan momen berharga Anda. Kunjungi studio kami sekarang dan rasakan keajaiban potret yang tak terlupakan.
                </p>
                <button className="btn rounded-md bg-blue text-white-grey border-blue hover:bg-[#6380BB] hover:border-[#6380BB] gap-2">
                  Pesan Sekarang!
                  {rightArrow()}
                </button>
              </>
            )}

            {session?.role === "user" && (
              <>
                <button className="btn rounded-md bg-blue text-white-grey border-blue hover:bg-[#6380BB] hover:border-[#6380BB] gap-2">
                  Lihat Foto Saya
                  {rightArrow()}
                </button>
              </>
            )}

            {session?.role === "admin" && (
              <>
                <p>
                Raih momen tak terlupakan dengan Moro Studio, self photo studio terbaik di Jogja dan Solo. Dengan fasilitas lengkap dan tim profesional, kami menghadirkan pengalaman foto yang kreatif dan berkualitas tinggi untuk mengabadikan momen berharga Anda. Kunjungi studio kami sekarang dan rasakan keajaiban potret yang tak terlupakan.
                </p>
                <button className="btn rounded-md bg-blue text-white-grey border-blue hover:bg-[#6380BB] hover:border-[#6380BB] gap-2">
                  Lihat Pesanan 
                  {rightArrow()}
                </button>
              </>
            )}
          </div>
        </div>
        <div className="mx-8 mt-8 flex flex-col sm:mx-12 md:mx-24 lg:mx-28 xl:mx-auto xl:max-w-6xl">
          <h1 className="mb-8 text-center text-3xl font-bold">Gambar</h1>
          <div className="carousel-center carousel rounded-box mb-8 space-x-4 bg-light-grey p-4">
            {homepage.data?.carousel.map((item) => (
              <div className="carousel-item">
                <img
                  src={item}
                  className="rounded-box"
                  style={{ height: "540px" }}
                />
              </div>
            ))}
          </div>
        </div>

        <footer className="footer bg-dark-grey md:grid-cols-4 p-8 text-base-content">
          <div className="md:ml-20">
            <Image
              className="block w-auto"
              src="/Logo Moro Teks Putih.png"
              alt="Logo Morostudio"
              width={100}
              height={100}
            />
          </div>
          <div className="mr-5 md:mt-3">
            <span className="font-bold text-white-grey">
              Moro Studio Jogja
            </span>
            <p className="text-white-grey">
              Jl. Demangan Baru, Mrican, Caturtunggal, Kec. Depok, Kabupaten
              Sleman, Daerah Istimewa Yogyakarta 55281
            </p>
          </div>
          <div className="mr-5 md:mt-3">
            <span className="font-bold text-white-grey">
              Moro Studio Solo
            </span>
            <p className="text-white-grey">
              CQQQ+W86, Pajang, Kec. Laweyan, Kota Surakarta, Jawa Tengah 57146
            </p>
          </div>
          <div className="md:mt-8 flex items-center">
            <BsInstagram className="text-2xl text-white-grey"/>
            <span className="text-white-grey">morostudio.id</span>
          </div>
        </footer>
      </main>
    </>
  );
};

export default Home;
