import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { CTA, CarouselSection, HeroSection } from "./homepage/templates";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const homepage = api.homepage.getSortedSections.useQuery();
  let homepageArray: JSX.Element[] = [];
  console.log(homepage);

  homepage.data?.forEach((section) => {
    if (section.order != 0) {
      if (section.type == "hero") {
        homepageArray.push(HeroSection(section));
      } else if (section.type == "carousel") {
        homepageArray.push(CarouselSection(section));
      } else if (section.type == "CTA") {
        homepageArray.push(CTA(section));
      }
    }
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Hello world</h1>
        <Link href={"/homepage/edit"}>Edit</Link>
        <div>{homepageArray}</div>
      </main>
    </>
  );
};

export default Home;
